services:
  iris:
    build:
      context: .
      args:
        IRIS_IMAGE: "${IRIS_IMAGE}"
        IRIS_TAG: "${IRIS_IMAGE_TAG}"
        IRIS_PW: "${IRIS_PW}"
    image: ${OUTPUT_IMAGE_NAME}:${OUTPUT_IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    volumes:
    - ./volumes/iris:/iris-shared
    command: 
    - "${LICENSE_KEY_PATTERN:+--key /iris-shared/license/iris.key}"

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:${IRIS_IMAGE_TAG}
    hostname: ${WEBGATEWAY_HOSTNAME}
    container_name: ${CONTAINER_NAME}-wg
    ports:
    - "${WEBSERVER_PORT}:80"
    - "${WEBSERVER_PORT_HTTPS}:443"
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./volumes/webgateway:/webgateway-shared

