Class Demo.SampleProduction Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="Demo.SampleProduction" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="XML File Service" Category="" ClassName="EnsLib.XML.FileService" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
